package com.example.healthmanagementorganization.Model;

import android.util.Log;

import java.util.Calendar;

public class Appointment {
    private String appointmentID;
    private String patientID;
    private String doctorID;
    private Calendar startTime;
    private Calendar endTime;

    /**
     * constructor
     */
    public Appointment() {
    }


    /**
     * set the appointmentID
     * the appointmentID is the combination of the patientID and the doctorID
     * the appointmentID is unique
     * the appointmentID is generated by the system
     */
    public void setAppointmentID() {
        String id = "";
        id += patientID;
        id += doctorID;
        id += startTime.get(Calendar.YEAR);
        id += startTime.get(Calendar.MONTH);
        id += startTime.get(Calendar.DAY_OF_MONTH);
        id += startTime.get(Calendar.HOUR_OF_DAY);
        id += startTime.get(Calendar.MINUTE);
        id += startTime.get(Calendar.SECOND);
        id += endTime.get(Calendar.HOUR_OF_DAY);
        id += endTime.get(Calendar.MINUTE);
        id += endTime.get(Calendar.SECOND);
        this.appointmentID = id;
    }


    /**
     * set the patientID
     *
     * @param patientID the patientID
     * @return true if the patientID is valid
     */
    public boolean setPatientID(String patientID) {
        // check if the patientID is valid
        if (patientID == null || patientID.isEmpty()) {
            return false;
        }

        this.patientID = patientID;
        return true;
    }

    /**
     * set the doctorID
     *
     * @param doctorID the doctorID
     * @return true if the doctorID is valid
     */
    public Appointment setDoctorID(String doctorID) {
        // check if the doctorID is valid
        if (doctorID == null || doctorID.isEmpty()) {
            return null;
        }

        this.doctorID = doctorID;
        return this;
    }

    /**
     * set the start time
     *
     * @param startTime the start time
     * @return true if the start time is valid
     */
    public Appointment setStartTime(Calendar startTime) {
        // check if the startTime is valid
        if (startTime == null) {
            return null;
        }
        // check if the startTime is after the current time
        if (startTime.before(Calendar.getInstance())) {
            return null;
        }
        this.startTime = startTime;
        return this;
    }

    /**
     * set the end time
     *
     * @param endTime the end time
     * @return true if the end time is valid
     */
    public Appointment setEndTime(Calendar endTime) {
        // check if the endTime is valid
        if (endTime == null) {
            return null;
        }
        // check if the endTime is after the current time
        if (endTime.before(Calendar.getInstance())) {
            return null;
        }
        this.endTime = endTime;
        return this;
    }


    /**
     * get the appointmentID
     *
     * @return the appointmentID
     */
    public String getAppointmentID() {
        return appointmentID;
    }


    public String getPatientID() {
        return patientID;
    }

    public String getDoctorID() {
        return doctorID;
    }

    public Calendar getStartTime() {
        return startTime;
    }

    public Calendar getEndTime() {
        return endTime;
    }
}
